// Generated by IcedCoffeeScript 1.8.0-e
(function() {
  var fs, http, map, server;

  http = require("http");

  map = require("through2-map");

  fs = require("fs");

  server = http.createServer(function(req, res) {
    if (req.method === "POST") {
      res.writeHead(200, {
        "content-type": "text/plain"
      });
      return req.pipe(map(function(chunk) {
        return chunk.toString().toUpperCase();
      })).pipe(res);
    }
  });

  server.listen(process.argv[2]);

}).call(this);
