// Generated by IcedCoffeeScript 1.8.0-e
(function() {
  var k, sum, v, _i, _len, _ref;

  sum = 0;

  _ref = process.argv;
  for (v = _i = 0, _len = _ref.length; _i < _len; v = ++_i) {
    k = _ref[v];
    if (v > 1) {
      sum += +k;
    }
  }

  console.log(sum);

}).call(this);
