// Generated by IcedCoffeeScript 1.8.0-e
(function() {
  var buf, fname, fs;

  fs = require("fs");

  fname = process.argv[2];

  buf = fs.readFileSync(fname);

  console.log(buf.toString().split("\n").length);

}).call(this);
