// Generated by IcedCoffeeScript 1.8.0-e
(function() {
  var fname, fs;

  fs = require("fs");

  fname = process.argv[2];

  fs.readFile(fname, function(err, buf) {
    return console.log(buf.toString().split("\n").length - 1);
  });

}).call(this);
