// Generated by IcedCoffeeScript 1.8.0-e
(function() {
  var dirpath, extname, fs, path;

  fs = require("fs");

  path = require("path");

  dirpath = process.argv[2];

  extname = "." + process.argv[3];

  fs.readdir(dirpath, function(err, files) {
    var file, _i, _len, _results;
    _results = [];
    for (_i = 0, _len = files.length; _i < _len; _i++) {
      file = files[_i];
      if ((path.extname(file)) === extname) {
        _results.push(console.log(file));
      }
    }
    return _results;
  });

}).call(this);
