// Generated by IcedCoffeeScript 1.8.0-e
(function() {
  var dirpath, err, extname, file, files, fs, iced, path, __iced_deferrals, __iced_k, __iced_k_noop;

  iced = require('iced-runtime');
  __iced_k = __iced_k_noop = function() {};

  fs = require("fs");

  path = require("path");

  dirpath = process.argv[2];

  extname = "." + process.argv[3];

  (function(_this) {
    return (function(__iced_k) {
      __iced_deferrals = new iced.Deferrals(__iced_k, {
        filename: "/home/wukc/learnyounode/ex5_2.iced"
      });
      fs.readdir(dirpath, __iced_deferrals.defer({
        assign_fn: (function() {
          return function() {
            err = arguments[0];
            return files = arguments[1];
          };
        })(),
        lineno: 4
      }));
      __iced_deferrals._fulfill();
    });
  })(this)((function(_this) {
    return function() {
      var _i, _len, _results;
      _results = [];
      for (_i = 0, _len = files.length; _i < _len; _i++) {
        file = files[_i];
        if ((path.extname(file)) === extname) {
          _results.push(console.log(file));
        }
      }
      return _results;
    };
  })(this));

}).call(this);
