// Generated by IcedCoffeeScript 1.8.0-e
(function() {
  var iced, __iced_k, __iced_k_noop;

  iced = require('iced-runtime');
  __iced_k = __iced_k_noop = function() {};

  module.exports = function(dir, ext, f) {
    var err, file, files, fs, path, ___iced_passed_deferral, __iced_deferrals, __iced_k;
    __iced_k = __iced_k_noop;
    ___iced_passed_deferral = iced.findDeferral(arguments);
    fs = require("fs");
    path = require("path");
    (function(_this) {
      return (function(__iced_k) {
        __iced_deferrals = new iced.Deferrals(__iced_k, {
          parent: ___iced_passed_deferral,
          filename: "/home/wukc/learnyounode/ex6-module.iced",
          funcname: "exports"
        });
        fs.readdir(dir, __iced_deferrals.defer({
          assign_fn: (function() {
            return function() {
              err = arguments[0];
              return files = arguments[1];
            };
          })(),
          lineno: 3
        }));
        __iced_deferrals._fulfill();
      });
    })(this)((function(_this) {
      return function() {
        if (err) {
          return f(err);
        }
        return f(null, (function() {
          var _i, _len, _results;
          _results = [];
          for (_i = 0, _len = files.length; _i < _len; _i++) {
            file = files[_i];
            if ((path.extname(file)) === "." + ext) {
              _results.push(file);
            }
          }
          return _results;
        })());
      };
    })(this));
  };

}).call(this);
