// Generated by IcedCoffeeScript 1.8.0-e
(function() {
  var bl, buf, http, iced, res, __iced_deferrals, __iced_k, __iced_k_noop;

  iced = require('iced-runtime');
  __iced_k = __iced_k_noop = function() {};

  http = require("http");

  bl = require("bl");

  buf = new bl();

  (function(_this) {
    return (function(__iced_k) {
      __iced_deferrals = new iced.Deferrals(__iced_k, {
        filename: "/home/wukc/learnyounode/ex8.iced"
      });
      http.get(process.argv[2], __iced_deferrals.defer({
        assign_fn: (function() {
          return function() {
            return res = arguments[0];
          };
        })(),
        lineno: 3
      }));
      __iced_deferrals._fulfill();
    });
  })(this)((function(_this) {
    return function() {
      res.setEncoding("utf8");
      res.on("data", function(data) {
        return buf.append(data);
      });
      res.on("error", console.error);
      return res.on("end", function(end) {
        console.log(buf.length);
        return console.log(buf.toString());
      });
    };
  })(this));

}).call(this);
