// Generated by IcedCoffeeScript 1.8.0-e
(function() {
  var fs, http, map, server;

  http = require("http");

  map = require("through2-map");

  fs = require("fs");

  server = http.createServer(function(req, res) {
    var data, date, hash, time;
    if (req.method === "GET") {
      data = require("url").parse(req.url, true);
      date = new Date(data["query"]["iso"]);
      time = date.getTime();
      hash = {};
      switch (data["pathname"]) {
        case "/api/parsetime":
          hash = {
            hour: date.getHours(),
            minute: date.getMinutes(),
            second: date.getSeconds()
          };
          break;
        case "/api/unixtime":
          hash = {
            unixtime: date.getTime()
          };
      }
      res.writeHead(200, {
        "content-type": "application/json"
      });
      return res.end(JSON.stringify(hash));
    }
  });

  server.listen(process.argv[2]);

}).call(this);
