// Generated by IcedCoffeeScript 1.8.0-e
(function() {
  var bl, buf, http, i, iced, k, r, res, str, url, urls, __iced_deferrals, __iced_k, __iced_k_noop;

  iced = require('iced-runtime');
  __iced_k = __iced_k_noop = function() {};

  http = require("http");

  bl = require("bl");

  buf = new bl();

  urls = (function() {
    var _i, _results;
    _results = [];
    for (k = _i = 2; _i <= 4; k = ++_i) {
      _results.push(process.argv[k]);
    }
    return _results;
  })();

  res = [];

  str = [];

  (function(_this) {
    return (function(__iced_k) {
      var _i, _len;
      __iced_deferrals = new iced.Deferrals(__iced_k, {
        filename: "/home/wukc/learnyounode/program.iced"
      });
      for (i = _i = 0, _len = urls.length; _i < _len; i = ++_i) {
        url = urls[i];
        http.get(url, __iced_deferrals.defer({
          assign_fn: (function(__slot_1, __slot_2) {
            return function() {
              return __slot_1[__slot_2] = arguments[0];
            };
          })(res, i),
          lineno: 8
        }));
      }
      __iced_deferrals._fulfill();
    });
  })(this)((function(_this) {
    return function() {
      (function(__iced_k) {
        var _i, _len;
        __iced_deferrals = new iced.Deferrals(__iced_k, {
          filename: "/home/wukc/learnyounode/program.iced"
        });
        for (i = _i = 0, _len = res.length; _i < _len; i = ++_i) {
          r = res[i];
          r.pipe(bl(function(err, data) {
            if (err) {
              return console.error(err);
            }
            str.push(data.toString());
            console.log(str);
            return __iced_deferrals.defer({
              lineno: 15
            });
          }));
        }
        __iced_deferrals._fulfill();
      })(function() {
        return console.log(str);
      });
    };
  })(this));

}).call(this);
